repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        additional_dependencies: [toml]
        language_version: python3.7

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
